name: CS6200
dependencies:
  - python=3.6
  - pip
  - pip:
      - numpy==1.18.1
      - elasticsearch==7.1.0
      - elasticsearch-dsl==7.1.0
      - nltk==3.4.5
      - protobuf==3.11.3
      - pytest==5.3.5
      - beautifulsoup4==4.8.2
      - tldextract==2.2.2
      - redis==3.4.1
      - hiredis==1.0.1
      - lxml==4.5.0
      - retrying==1.3.3
      - sqlalchemy==1.3.13
      - mysqlclient==1.4.6
      - redisbloom==0.3.2