# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: termvector.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='termvector.proto',
    package='',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x10termvector.proto\"\'\n\x06TfInfo\x12\n\n\x02tf\x18\x01 \x01(\x05\x12\x11\n\tpositions\x18\x02 \x03(\x05\"\x88\x01\n\nTermVector\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x0b\n\x03ttf\x18\x02 \x01(\x05\x12\'\n\x06tfInfo\x18\x03 \x03(\x0b\x32\x17.TermVector.TfInfoEntry\x1a\x36\n\x0bTfInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x16\n\x05value\x18\x02 \x01(\x0b\x32\x07.TfInfo:\x02\x38\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TFINFO = _descriptor.Descriptor(
    name='TfInfo',
    full_name='TfInfo',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='tf', full_name='TfInfo.tf', index=0,
            number=1, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='positions', full_name='TfInfo.positions', index=1,
            number=2, type=5, cpp_type=1, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=20,
    serialized_end=59,
)

_TERMVECTOR_TFINFOENTRY = _descriptor.Descriptor(
    name='TfInfoEntry',
    full_name='TermVector.TfInfoEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key', full_name='TermVector.TfInfoEntry.key', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='value', full_name='TermVector.TfInfoEntry.value', index=1,
            number=2, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=144,
    serialized_end=198,
)

_TERMVECTOR = _descriptor.Descriptor(
    name='TermVector',
    full_name='TermVector',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='term', full_name='TermVector.term', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='ttf', full_name='TermVector.ttf', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='tfInfo', full_name='TermVector.tfInfo', index=2,
            number=3, type=11, cpp_type=10, label=3,
            has_default_value=False, default_value=[],
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[_TERMVECTOR_TFINFOENTRY, ],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=62,
    serialized_end=198,
)

_TERMVECTOR_TFINFOENTRY.fields_by_name['value'].message_type = _TFINFO
_TERMVECTOR_TFINFOENTRY.containing_type = _TERMVECTOR
_TERMVECTOR.fields_by_name['tfInfo'].message_type = _TERMVECTOR_TFINFOENTRY
DESCRIPTOR.message_types_by_name['TfInfo'] = _TFINFO
DESCRIPTOR.message_types_by_name['TermVector'] = _TERMVECTOR

TfInfo = _reflection.GeneratedProtocolMessageType('TfInfo', (_message.Message,), dict(
    DESCRIPTOR=_TFINFO,
    __module__='termvector_pb2'
    # @@protoc_insertion_point(class_scope:TfInfo)
))
_sym_db.RegisterMessage(TfInfo)

TermVector = _reflection.GeneratedProtocolMessageType('TermVector', (_message.Message,), dict(

    TfInfoEntry=_reflection.GeneratedProtocolMessageType('TfInfoEntry', (_message.Message,), dict(
        DESCRIPTOR=_TERMVECTOR_TFINFOENTRY,
        __module__='termvector_pb2'
        # @@protoc_insertion_point(class_scope:TermVector.TfInfoEntry)
    ))
    ,
    DESCRIPTOR=_TERMVECTOR,
    __module__='termvector_pb2'
    # @@protoc_insertion_point(class_scope:TermVector)
))
_sym_db.RegisterMessage(TermVector)
_sym_db.RegisterMessage(TermVector.TfInfoEntry)

_TERMVECTOR_TFINFOENTRY.has_options = True
_TERMVECTOR_TFINFOENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
